# Remote Theme Configuration
remote_theme: mmistakes/minimal-mistakes@4.26.2

# Site Metadata
title: "Don't Panic, Organize!"
description: "Resources for Community Resilience"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Header and Footer Settings
header:
  nav:
    - enabled: true

# Defaults for Posts
defaults:
  - scope:
      path: "" # Applies to all files in the project
      type: "posts"
    values:
      layout: "single"

# Defaults for Pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "sample"

# Optional Settings for Minimal Mistakes
theme_skin: "default"
sass:
  custom: "assets/css/main.scss"

# Navigation Links
navigation:
  - title: "About"
    url: /
  - title: "Resources"
    url: /resources/
    sublinks:
      - title: "Guidelines"
        url: /guidelines/
  - title: "Workshops"
    url: /workshops/
  - title: "Contact"
    url: /about/

# Site Author
author:
  name             : "Community Tech NY"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
#  bio              : "I am an **amazing** person."
#  location         : "Somewhere"
  email            : "info@communitytechny.org"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:info@communitytechny.org"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://www.communitytechny.org/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/Community-Tech-Lab"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://www.instagram.com/commtechny/"

