# Remote Theme Configuration
remote_theme: mmistakes/minimal-mistakes@4.26.2

# Site Metadata
title: "Resources for Community Resilience"
description: "Workshops & guidelines to help communities get prepared"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Defaults for Posts
defaults:
  - scope:
      path: "" # Applies to all files in the project
      type: "posts"
    values:
      layout: "single"

# Optional Settings for Minimal Mistakes
theme_skin: "default"

