remote_theme: minimal-mistakes-jekyll # or mmistakes/minimal-mistakes@4.26.2
title: Resources for Community Resilience
description: Workshops & guidelines to help communities get prepared

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
jekyll-include-cache
