# Remote Theme Configuration
remote_theme: mmistakes/minimal-mistakes@4.26.2

# Site Metadata
title: "Don't Panic, Organize!"
description: "Resources for Community Resilience"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Header and Footer Settings
# header:
#  nav:
#    - enabled: true

# Defaults for Posts
defaults:
  - scope:
      path: "" # Applies to all files in the project
      type: "posts"
    values:
      layout: "single"

# Defaults for Pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "sample"

# Optional Settings for Minimal Mistakes
theme_skin: "default"

theme:
  sass:
    custom: "assets/css/custom.css"


